---
title: "accuracy"
author: "Polyphony J. Bruna"
date: "2025-01-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
```

```{r}
performance_data1 <- read.csv("data/s23_randreset_batch1/performance.csv")

performance_data2 <- read.csv("data/s23_randreset_batch2/performance.csv") %>%
  mutate(run_idx = run_idx + 8)

performance_data3 <- read.csv("data/s23_randreset_batch3/performance.csv") %>%
  mutate(run_idx = run_idx + 16)

performance_data4 <- read.csv("data/s23_randreset_batch4/performance.csv") %>%
  mutate(run_idx = run_idx + 24)

performance_data5 <- read.csv("data/s23_randreset_batch5/performance.csv") %>%
  mutate(run_idx = run_idx + 32)
```

```{r}
performance_data <- rbind(performance_data1, performance_data2, performance_data3, performance_data4, performance_data5) %>%
  filter(timestep!=1)
```

```{r}
# Check individual esn performance

performance_data %>%
  filter(model!="joint") %>%
  group_by(model, coupling, signal_idx) %>%
  summarise(m = mean(correct)) %>%
  group_by(model, coupling) %>%
  summarise(M = mean(m), SE = sd(m)/sqrt(n())) %>%
  filter(coupling==0)
```

```{r}
joint_esn_perf <- performance_data %>% 
  filter(model=="joint") %>%
  group_by(coupling, run_idx, signal_idx) %>%
  summarise(avg_sig_acc = mean(correct)) %>%
  group_by(coupling, signal_idx) %>%
  summarise(avg_over_runs = mean(avg_sig_acc)) %>%
  group_by(coupling) %>%
  summarise(m = mean(avg_over_runs), se = sd(avg_over_runs)/sqrt(n()))

ggplot(joint_esn_perf, aes(x=coupling, y=m)) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(x="Coupling", y="Accuracy (%)") +
  theme_bw()
```

```{r}
joint_perf_timeseries <- performance_data %>%
  filter(model=="joint") %>%
  group_by(coupling, run_idx, signal_idx) %>%
  mutate(norm_t = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(norm_t = round(norm_t, 1) * 10) %>%
  group_by(coupling, run_idx, signal_idx) %>%
  arrange(norm_t, .by_group = TRUE) %>%
  mutate(cuml_cor = cumsum(correct),
         cuml_total = row_number(),
         cuml_acc = cuml_cor/cuml_total) %>%
  group_by(coupling, signal_idx, norm_t) %>%
  summarise(acc_over_runs = mean(cuml_acc)) %>%
  group_by(coupling, norm_t) %>%
  summarise(m = mean(acc_over_runs), se = sd(acc_over_runs)/sqrt(n()))

ggplot(joint_perf_timeseries, aes(x=norm_t, y=m)) +
  facet_wrap(~coupling) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(x="Time (normalized)", y="Accuracy (%)") +
  geom_hline(yintercept=0.5, linetype="dotted") +
  theme_bw()
```




