---
title: "esn_with_fb"
author: "Polyphony J. Bruna"
date: "2025-01-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
pred <- read.csv("data/esn_fb/predictions.csv")
targ <- read.csv("data/esn_fb/targets.csv")
meta_data <- read.csv("data/esn_fb/meta_data.csv")

colnames(targ) <- paste0('T', colnames(targ))
```

```{r}
data <- cbind(pred, targ, meta_data) %>%
  group_by(run_idx, signal_idx) %>%
  mutate(timestep = row_number())
```

```{r}
performance_data <- data %>%
  rowwise() %>%
  mutate(response = which.max(c(X0, X1, X2, X3, X4, X5, X6, X7, X8)),
         target = which.max(c(TX0, TX1, TX2, TX3, TX4, TX5, TX6, TX7, TX8)),
         correct = ifelse(response==target, 1, 0))
```

```{r}
performance_data <- performance_data %>%
  filter(timestep!=1) %>%
  mutate(run_idx = factor(run_idx),
         signal_idx = factor(signal_idx),
         target = factor(target))
```

```{r}
performance_data %>%
  group_by(run_idx, signal_idx) %>%
  mutate(signal_avg = mean(correct)) %>%
  group_by(run_idx) %>%
  summarise(m = mean(signal_avg), se = sd(signal_avg)/sqrt(n()))
```

```{r}
performance_data %>%
  group_by(signal_idx, target) %>%
  mutate(signal_avg = mean(correct)) %>%
  group_by(target) %>%
  summarise(m = mean(signal_avg), se = sd(signal_avg)/sqrt(n()))
```

```{r}
acc <- performance_data %>%
  group_by(run_idx, target, signal_idx) %>%
  mutate(norm_t = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(norm_t = round(norm_t, 1) * 10) %>%
  group_by(target, signal_idx, norm_t) %>%
  summarise(acc_over_runs = mean(correct)) %>%
  group_by(target, norm_t) %>%
  summarise(m = mean(acc_over_runs), se = sd(acc_over_runs)/sqrt(n()))

intgr_acc <- performance_data %>%
  group_by(run_idx, target, signal_idx) %>%
  mutate(norm_t = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(norm_t = round(norm_t, 1) * 10) %>%
  group_by(run_idx, target, signal_idx) %>%
  arrange(norm_t, .by_group = TRUE) %>%
  mutate(cuml_cor = cumsum(correct),
         cuml_total = row_number(),
         cuml_acc = cuml_cor/cuml_total) %>%
  group_by(target, signal_idx, norm_t) %>%
  summarise(acc_over_runs = mean(cuml_acc)) %>%
  group_by(target, norm_t) %>%
  summarise(m = mean(acc_over_runs), se = sd(acc_over_runs)/sqrt(n()))
  
ggplot(acc, aes(x=norm_t, y=m)) +
  facet_wrap(~target) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title = "Accuracy", x="Time (normalized)", y="Accuracy (%)") +
  theme_bw()

ggplot(intgr_acc, aes(x=norm_t, y=m)) +
  facet_wrap(~target) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title = "Integrating over time", x="Time (normalized)", y="Accuracy (%)") +
  theme_bw()
```

```{r}
acc <- performance_data %>%
  group_by(run_idx, signal_idx) %>%
  mutate(norm_t = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(norm_t = round(norm_t, 1) * 10) %>%
  group_by(signal_idx, norm_t) %>%
  summarise(acc_over_runs = mean(correct)) %>%
  group_by(norm_t) %>%
  summarise(m = mean(acc_over_runs), se = sd(acc_over_runs)/sqrt(n()))

intgr_acc <- performance_data %>%
  group_by(run_idx, signal_idx) %>%
  mutate(norm_t = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(norm_t = round(norm_t, 1) * 10) %>%
  group_by(run_idx, signal_idx) %>%
  arrange(norm_t, .by_group = TRUE) %>%
  mutate(cuml_cor = cumsum(correct),
         cuml_total = row_number(),
         cuml_acc = cuml_cor/cuml_total) %>%
  group_by(signal_idx, norm_t) %>%
  summarise(acc_over_runs = mean(cuml_acc)) %>%
  group_by(norm_t) %>%
  summarise(m = mean(acc_over_runs), se = sd(acc_over_runs)/sqrt(n()))
  
ggplot(acc, aes(x=norm_t, y=m)) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title = "Accuracy", x="Time (normalized)", y="Accuracy (%)") +
  theme_bw()

ggplot(intgr_acc, aes(x=norm_t, y=m)) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title = "Integrating over time", x="Time (normalized)", y="Accuracy (%)") +
  theme_bw()
```

