---
title: "performance analyses"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggpubr)
library(colorspace)
```

# homogenous nets

```{r}
accuracies_raw <- read_csv("C:/Users/bruna/Desktop/GitHub/coupled-esns/data/v2/accuracies_r=500_reset=zero_final.csv") %>%
  filter(noise_1 >= noise_2)
```

```{r}
# avg_acc <- accuracies_raw %>%
#  pivot_longer(cols = !c(run, condition, noise_1, noise_2), names_to = "measure", values_to = "value") %>%
#  group_by(condition, noise_1, noise_2, measure) %>%
#  summarise(m = mean(value), se = sd(value)/sqrt(n()))
# 
# avg_acc$condition <- factor(avg_acc$condition, levels = c("auto", "allo", "poly_parallel", "poly_integr"))
# avg_acc$measure <- factor(avg_acc$measure, levels = c("lower", "upper", "avg", "joint"))
# 
# ggplot(avg_acc, aes(x=condition, y=m, color=measure, fill=measure)) +
#  facet_grid(noise_1~noise_2, switch = "y") +
#  geom_col(position = position_dodge(0.9)) +
#  geom_errorbar(aes(x=condition, ymin=m-se, ymax=m+se), color="black", width = 0.4, position = position_dodge(0.9)) +
#  scale_y_continuous(limits = c(0, 1), breaks = seq(0,1,0.2)) +
#  labs(y = "avg_pcorrect") +
#  theme_minimal() +
#  theme(axis.text.x = element_text(angle = 45, hjust = 1),
#        axis.text.y = element_blank())
```

```{r}
acc_cleaned <- accuracies_raw %>%
  pivot_longer(cols = !c(run, condition, noise_1, noise_2), names_to = "measure", values_to = "value") %>%
  filter(condition=="auto" | (condition %in% c("poly_parallel", "poly_integr") & measure == "joint")) %>%
  mutate(measure = case_when(
    condition=="auto" & measure=="joint" ~ "woc",
    condition=="poly_parallel" & measure=="joint" ~ "dyad_parall",
    condition=="poly_integr" & measure=="joint" ~ "dyad_integr",
    measure=="upper" ~ "max",
    measure=="lower" ~ "min",
    measure=="avg" ~ "avg",
    TRUE ~ measure
  )) %>%
  select(!condition)

acc_cleaned_summary <- acc_cleaned %>%
  group_by(noise_1, noise_2, measure) %>%
  summarise(m = mean(value), se = sd(value)/sqrt(n()))

acc_cleaned_summary$measure <- factor(acc_cleaned_summary$measure, levels = c("min", "max", "avg", "woc", "dyad_parall", "dyad_integr"))
acc_cleaned_summary$inequality <- factor(abs(acc_cleaned_summary$noise_1-acc_cleaned_summary$noise_2))

ggplot(acc_cleaned_summary, aes(x=measure, y=m, color=inequality, fill=inequality)) +
  facet_grid(noise_1~noise_2, switch = "y") +
  geom_col(position = position_dodge(0.9)) +
  geom_errorbar(aes(x=measure, ymin=m-se, ymax=m+se), color="black", width = 0.4, position = position_dodge(0.9)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0,1,0.2)) +
  scale_color_viridis_d() +
  scale_fill_viridis_d() +
  labs(y = "avg_pcorrect") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_blank())
```

```{r}
acc_ratio <- acc_cleaned %>%
  group_by(noise_1, noise_2, measure) %>%
  pivot_wider(names_from = measure, values_from = value) %>%
  mutate(min_max = min / max,
         dyadp_max = dyad_parall / max,
         dyadi_max = dyad_integr / max,
         noise = case_when(noise_1==0.0 & noise_2==0.0 ~ "none", noise_1==noise_2 ~ "equal", T ~ "unequal")) %>%
  ungroup() %>%
  select(noise_1, noise_2, noise, min_max, dyadp_max, dyadi_max) %>%
  pivot_longer(cols = !c(noise_1, noise_2, noise, min_max), names_to = "measure", values_to = "value")

acc_ratio$noise <- factor(acc_ratio$noise, levels = c("none", "unequal", "equal"), labels = c("no noise", "unequal noise", "equal noise"))
acc_ratio$measure <- factor(acc_ratio$measure, levels = c("dyadp_max", "dyadi_max"), labels = c("dyad_parall", "dyad_integr"))

ggplot(acc_ratio %>% filter(noise_1 != 0.5, noise_2 != 0.5),
       aes(x=min_max, y=value, color=noise, shape=noise)) +
  facet_grid(measure~.) +
  geom_point(alpha=0.8, size=2, stroke=1.1) +
  geom_smooth(method = "lm", aes(group = 1), color = "black", se = F) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_manual(values = cols) + 
  scale_shape_manual(values = c("no noise" = 0, "unequal noise" = 1, "equal noise" = 2)) +
  xlim(0,1) +
  # ylim(0.4,1.6) +
  labs(x = expression(P[min] / P[max]), y = expression(P[dyad] / P[max])) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        strip.text = element_text(size=10))
```

```{r}
acc_ratio$noise <- factor(acc_ratio$noise, levels = c("equal", "unequal", "none"))

acc_ratio_summary <- acc_ratio %>%
  group_by(noise, measure) %>%
  summarise(m = mean(value), se = sd(value)/sqrt(n()), .groups = "drop")

ggplot(acc_ratio, aes(x=noise, y=value)) +
  facet_wrap(~measure) +
  geom_col(data = acc_ratio_summary,
           aes(x = noise, y = m), fill = "grey", position = position_dodge(0.9), inherit.aes = FALSE) +
  geom_errorbar(data = acc_ratio_summary,
                aes(x = noise, ymin = m - se, ymax = m + se), width = 0.4, position = position_dodge(0.9), inherit.aes = FALSE) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(y="dyad_max", x="noise condition") +
  theme_minimal()
```

```{r}
acc_ratio_bahr <- acc_cleaned %>%
  filter(noise_1 %in% c(0.2, 0.3), noise_2 %in% c(0.2, 0.3)) %>%
  group_by(noise_1, noise_2, measure) %>%
  pivot_wider(names_from = measure, values_from = value) %>%
  mutate(min_max = min / max,
         dyadp_max = dyad_parall / max,
         dyadi_max = dyad_integr / max,
         noise = case_when(noise_1==0.2 & noise_2==0.2 ~ "none", noise_1==noise_2 ~ "equal", T ~ "unequal")) %>%
  ungroup() %>%
  select(noise, min_max, dyadp_max, dyadi_max) %>%
  pivot_longer(cols = !c(noise, min_max), names_to = "measure", values_to = "value")

acc_ratio_bahr$measure <- factor(acc_ratio_bahr$measure, levels = c("dyadp_max", "dyadi_max"), labels = c("dyad_parall", "dyad_integr"))
acc_ratio_bahr$noise <- factor(acc_ratio_bahr$noise, levels = c("equal", "unequal", "none"))

acc_ratio_bahr_summary <- acc_ratio_bahr %>%
  group_by(noise, measure) %>%
  summarise(m = mean(value), se = sd(value)/sqrt(n()), .groups = "drop")

ggplot(acc_ratio_bahr, aes(x=noise, y=value)) +
  facet_wrap(~measure) +
  geom_col(data = acc_ratio_bahr_summary,
           aes(x = noise, y = m), fill = "grey", position = position_dodge(0.9), inherit.aes = FALSE) +
  geom_errorbar(data = acc_ratio_bahr_summary,
                aes(x = noise, ymin = m - se, ymax = m + se), width = 0.4, position = position_dodge(0.9), inherit.aes = FALSE) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(y="dyad_max", x="noise condition") +
  theme_minimal()
```

# heterogeneous nets

```{r}
accuracies_raw <- read_csv("C:/Users/bruna/Desktop/GitHub/coupled-esns/data/v2/accuracies_N=100_final.csv")
```

```{r}
acc_cleaned <- accuracies_raw %>%
  pivot_longer(cols = !c(run, condition, noise_1, noise_2), names_to = "measure", values_to = "value") %>%
  filter(condition=="auto" | (condition %in% c("poly_parall", "poly_integr") & measure == "joint")) %>%
  mutate(measure = case_when(
    condition=="auto" & measure=="joint" ~ "woc",
    condition=="poly_parall" & measure=="joint" ~ "dyad_parall",
    condition=="poly_integr" & measure=="joint" ~ "dyad_integr",
    measure=="upper" ~ "max",
    measure=="lower" ~ "min",
    measure=="avg" ~ "avg",
    TRUE ~ measure
  )) %>%
  select(!condition)
```

```{r}
acc_ratio <- acc_cleaned %>%
  group_by(noise_1, noise_2, measure) %>%
  pivot_wider(names_from = measure, values_from = value) %>%
  mutate(min_max = min / max,
         dyadp_max = dyad_parall / max,
         dyadi_max = dyad_integr / max,
         noise = case_when(noise_1==0.0 & noise_2==0.0 ~ "none", noise_1==noise_2 ~ "equal", T ~ "unequal")) %>%
  ungroup() %>%
  select(noise_1, noise_2, noise, min_max, dyadp_max, dyadi_max) %>%
  pivot_longer(cols = !c(noise_1, noise_2, noise, min_max), names_to = "measure", values_to = "value")

acc_ratio$noise <- factor(acc_ratio$noise, levels = c("none", "unequal", "equal"), labels = c("no noise", "unequal noise", "equal noise"))
acc_ratio$measure <- factor(acc_ratio$measure, levels = c("dyadp_max", "dyadi_max"), labels = c("dyad_parall", "dyad_integr"))
```

```{r}
cols <- sequential_hcl(5, palette = "batlow")[3:1]

ggplot(acc_ratio %>% filter(noise_1 != 0.5, noise_2 != 0.5),
       aes(x=min_max, y=value, color=noise, shape=noise)) +
  facet_grid(measure~.) +
  geom_point(alpha=0.8, size=2, stroke=1.1) +
  geom_smooth(method = "lm", aes(group = 1), color = "black", se = F) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_manual(values = cols) + 
  scale_shape_manual(values = c("no noise" = 0, "unequal noise" = 1, "equal noise" = 2)) +
  xlim(0,1) +
  # ylim(0.4,1.6) +
  labs(x = expression(P[min] / P[max]), y = expression(P[dyad] / P[max])) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        strip.text = element_text(size=10))

# ggsave(filename = "ratios_nsigma=1.0.png", bg = "white", width=7, height=7)
```

```{r}
cols <- sequential_hcl(5, palette = "batlow")[3:1]

ggplot(acc_ratio %>% filter(noise_1 != 1.0, noise_2 != 1.0),
       aes(x=min_max, y=value, color=noise, shape=noise)) +
  facet_grid(measure~.) +
  geom_point(alpha=0.8, size=2, stroke=1.1) +
  geom_smooth(method = "lm", aes(group = 1), color = "black", se = F) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_manual(values = cols) + 
  scale_shape_manual(values = c("no noise" = 0, "unequal noise" = 1, "equal noise" = 2)) +
  xlim(0,1) +
  # ylim(0.4,1.6) +
  labs(x = expression(P[min] / P[max]), y = expression(P[dyad] / P[max])) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size=10),
        strip.text = element_text(size=10))

# ggsave(filename = "ratios_nsigma=0.5.png", bg = "white", width=7, height=7)
```

```{r}
acc_ratio_summary <- acc_ratio %>%
  filter(noise_1 != 1.0, noise_2 != 1.0) %>%
  group_by(noise, measure) %>%
  summarise(m = mean(value), se = sd(value)/sqrt(n()), .groups = "drop")

acc_ratio_summary$noise <- factor(acc_ratio_summary$noise, levels = c("equal noise", "unequal noise", "no noise"))

ggplot(acc_ratio, aes(x=noise, y=value)) +
  facet_wrap(~measure) +
  geom_col(data = acc_ratio_summary,
          aes(x = noise, y = m), fill = "grey", position = position_dodge(0.9), inherit.aes = FALSE) +
  geom_errorbar(data = acc_ratio_summary,
               aes(x = noise, ymin = m - se, ymax = m + se), width = 0.4, position = position_dodge(0.9), inherit.aes = FALSE) +
  # geom_jitter(alpha=0.1, width = 0.05, position = position_dodge(0.9)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(y=expression(P[dyad] / P[max])) +
  theme_minimal() +
  theme(axis.title.x = element_blank())
```

```{r}
acc_ratio_summary <- acc_ratio %>%
  filter(noise_1 != 0.5, noise_2 != 0.5) %>%
  group_by(noise, measure) %>%
  summarise(m = mean(value), se = sd(value)/sqrt(n()), .groups = "drop")

acc_ratio_summary$noise <- factor(acc_ratio_summary$noise, levels = c("equal noise", "unequal noise", "no noise"))

ggplot(acc_ratio, aes(x=noise, y=value)) +
  facet_wrap(~measure) +
  geom_col(data = acc_ratio_summary,
          aes(x = noise, y = m), fill = "grey", position = position_dodge(0.9), inherit.aes = FALSE) +
  geom_errorbar(data = acc_ratio_summary,
               aes(x = noise, ymin = m - se, ymax = m + se), width = 0.4, position = position_dodge(0.9), inherit.aes = FALSE) +
  # geom_jitter(alpha=0.1, width = 0.05, position = position_dodge(0.9)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(y=expression(P[dyad] / P[max])) +
  theme_minimal() +
  theme(axis.title.x = element_blank())
```

