---
title: "ratio plots"
output: html_document
date: "2025-11-02"
---

```{r}
library(tidyverse)
library(ggpubr)
library(colorspace)
library(lmerTest)
library(emmeans)
```


# ratios

```{r} 
key <- "bxbr"

accuracies_raw <- read_csv(paste0("C:/Users/bruna/Desktop/GitHub/coupled-esns/data/v3/accuracies_N=20_", key, "_final.csv"))
```

```{r}
acc_cleaned <- accuracies_raw %>%
  pivot_longer(cols = !c(run, condition, noise_1, noise_2), names_to = "measure", values_to = "value") %>%
  filter(condition=="auto" | (condition == "poly" & measure == "joint")) %>%
  mutate(measure = case_when(
    condition=="auto" & measure=="joint" ~ "d_integr",
    condition=="poly" & measure=="joint" ~ "d_intera",
    measure=="upper" ~ "max",
    measure=="lower" ~ "min",
    measure=="avg" ~ "avg",
    TRUE ~ measure
  )) %>%
  select(!condition)
```

```{r}
acc_ratio <- acc_cleaned %>%
  group_by(noise_1, noise_2, measure) %>%
  pivot_wider(names_from = measure, values_from = value) %>%
  mutate(min_max = min / max,
         dintegr_max = d_integr / max,
         dintera_max = d_intera / max,
         noise = case_when(noise_1==0.0 & noise_2==0.0 ~ "no noise",
                           noise_1==noise_2 ~ "equal noise",
                           T ~ "unequal noise")) %>%
  ungroup() %>%
  select(noise_1, noise_2, noise, min_max, dintegr_max, dintera_max) %>%
  pivot_longer(cols = !c(noise_1, noise_2, noise, min_max), names_to = "measure", values_to = "dyad_max") %>%
  mutate(measure = case_when(measure=="dintegr_max" ~ "d_integr", measure=="dintera_max" ~ "d_intera"))

acc_ratio$noise <- factor(acc_ratio$noise, levels = c("no noise", "unequal noise", "equal noise"))
acc_ratio$measure <- factor(acc_ratio$measure, levels = c("d_integr", "d_intera"), labels = c("self-feedback", "pooled-feedback"))
```

```{r}
# prep data

sigma_ambient <- 0.5
sigma_input <- 2

acc_ratio_ambient <- acc_ratio %>%
  filter(noise_1 %in% c(sigma_ambient, sigma_input), noise_2 %in% c(sigma_ambient, sigma_input)) %>%
  mutate(noise = case_when(noise_1==sigma_ambient & noise_2==sigma_ambient ~ "no noise",
                           T ~ noise),
         noise = factor(noise, levels = c("no noise", "unequal noise", "equal noise")))

beta_df <- acc_ratio_ambient %>%
  group_by(measure) %>%
  summarise(beta = coef(lm(dyad_max ~ min_max))[2], .groups = "drop") %>%
  mutate(x = 0.4, y = 1.9)


# plot

ggplot(acc_ratio_ambient, aes(x=min_max, y=dyad_max)) +
  facet_wrap(~measure, labeller = labeller(measure = c("self-feedback" = "no coupling,\nself-feedback",
                                                       "pooled-feedback" = "coupling via\npooled-feedback"))) +
  
  # annotate plot
  annotate("segment", x=0.1, xend=0.1, y=1.1, yend=1.9, arrow=arrow(length=unit(0.2, "cm")), color="black") +
  annotate("segment", x=0.1, xend=0.1, y=0.9, yend=0.1, arrow=arrow(length=unit(0.2, "cm")), color="black") +
  annotate("text", x=0.05, y=1.5, label="gain", hjust=0.5, size=7, angle=90) +
  annotate("text", x=0.05, y=0.5, label="loss", hjust=0.5, size=7, angle=90) +
  geom_segment(aes(x=0, xend=1, y=1, yend=1), color="black") +
  
  # plot data
  geom_point(aes(shape = noise, color = dyad_max >= 1), size = 3, stroke = 1.5) +
  geom_smooth(method = "lm", aes(group=1), color = "black", se = F) +
  scale_shape_manual(values = c("no noise" = 0, "unequal noise" = 1, "equal noise" = 2)) +
  scale_color_manual(values = c("TRUE" = "blue3", "FALSE" = "red3")) +
  scale_x_continuous(limits = c(0, 1.1), breaks = c(0.0, 0.5, 1.0)) +
  scale_y_continuous(limits = c(0, 2.1), breaks = c(0.0, 1.0, 2.0)) +
  labs(x = expression(italic(P[min] / P[max])),
       y = expression(italic(P[dyad] / P[max]))) +
  geom_text(data = beta_df,
            aes(x=x, y=y,
                label=paste0("β = ", round(beta,2))), inherit.aes = FALSE, hjust = 1, size = 7) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.text = element_text(size=26),
        legend.position = "bottom",
        legend.key.spacing = unit(1.5, 'cm'),
        axis.text = element_text(size=26),
        axis.title = element_text(size=28),
        strip.text = element_text(size=28)) +
  guides(color = "none")
  
# ggsave(filename = paste0("v3_ratios_", key, "_noise=", sigma_input, "_ambient=", sigma_ambient, ".png"), bg = "white", width=12, height=7)
```


# stats

```{r}
acc_ratio_test <- acc_ratio_ambient %>%
  select(noise, measure, min_max, dyad_max) %>%
  mutate(dyad = rep(1:ceiling(n()/2), each = 2))
```

```{r}
summary(lm(dyad_max ~ min_max, data = acc_ratio_test %>% filter(measure=="self-feedback")))
summary(lm(dyad_max ~ min_max, data = acc_ratio_test %>% filter(measure=="pooled-feedback")))
```

```{r}
get_points <- function(model) {
  b0 <- coef(model)[1]
  b1 <- coef(model)[2]
  c(
    x_intercept = -b0 / b1,
    x_at_y1     = (1 - b0) / b1
  )
}

m_self <- lm(dyad_max ~ min_max,
             data = acc_ratio_test %>% filter(measure == "self-feedback"))

m_pooled <- lm(dyad_max ~ min_max,
               data = acc_ratio_test %>% filter(measure == "pooled-feedback"))

get_points(m_self)
get_points(m_pooled)
```

```{r}
summary(lmer(dyad_max ~ min_max*measure + (1|dyad), data = acc_ratio_test))
```

```{r}
acc_ratio_test$dyad_max_centered <- acc_ratio_test$dyad_max - 1

lmer_centered <- lmer(dyad_max_centered ~ min_max*measure + (1|dyad), data = acc_ratio_test)

emm <- emmeans(
  lmer_centered,
  ~ measure | min_max,
  at = list(min_max = c(1.0, 0.75, 0.5, 0.25, 0))
)

summary(emm, infer = TRUE)
```


# preds

```{r}
mock_df <- data.frame(x=c(0.15, 1, 0.15, 1),
                      y=c(0.25, 2, 0, 1),
                      pred = c("dyadic advantage", "dyadic advantage", "null model", "null model"))

ggplot(mock_df, aes(x=x, y=y, linetype=pred)) +
  geom_line(linewidth = 1) +
  geom_segment(aes(x=0, xend=1, y=1, yend=1)) +
  annotate("segment", x=0.1, xend=0.1, y=1.1, yend=1.9, arrow=arrow(length=unit(0.2, "cm"))) +
  annotate("segment", x=0.1, xend=0.1, y=0.9, yend=0.1, arrow=arrow(length=unit(0.2, "cm"))) +
  annotate("text", x=0.05, y=1.5, label="gain", hjust=0.5, size=7, angle=90) +
  annotate("text", x=0.05, y=0.5, label="loss", hjust=0.5, size=7, angle=90) +
  labs(x = "min / max",
       y = "dyad / max") +
  theme_minimal() +
  theme(axis.text = element_blank(),
        axis.title = element_text(size=28),
        panel.grid.minor = element_blank(),
        legend.position = c(0.45, 0.8),
        legend.text = element_text(size=26),
        legend.title = element_blank()) +
  guides(linetype = guide_legend(override.aes = list(linewidth = 0.6)))

# ggsave(filename = "manuscript_figs/theory_trends.png", bg = "white", width = 7, height = 6)
```

