---
title: "a_new_hope"
author: "Polyphony J. Bruna"
date: "2025-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
library(matrixStats)
```

# process data

```{r}
# data <- data.frame(
# X0 = numeric(),
# X1 = numeric(),
# X2 = numeric(),
# X3 = numeric(),
# X4 = numeric(),
# X5 = numeric(),
# X6 = numeric(),
# X7 = numeric(),
# X8 = numeric(),
# TX0 = numeric(),
# TX1 = numeric(),
# TX2 = numeric(),
# TX3 = numeric(),
# TX4 = numeric(),
# TX5 = numeric(),
# TX6 = numeric(),
# TX7 = numeric(),
# TX8 = numeric(),
# model = character(),
# coupling = numeric(),
# run_idx = numeric(),
# signal_idx = numeric(),
# timestep = numeric())
# 
# for(i in c(0:4)){
# y1 <- read.csv(paste0("data/noisy_a_new_hope_batch", i+1, "/Y1_n=0.3.csv")) %>%
#   mutate(model = "1")
# 
# y2 <- read.csv(paste0("data/noisy_a_new_hope_batch", i+1, "/Y2_n=0.3.csv")) %>%
#   mutate(model = "2")
# 
# yjoint <- data.frame("X0" = rowMeans(cbind(y1$X0, y2$X0)),
#                      "X1" = rowMeans(cbind(y1$X1, y2$X1)),
#                      "X2" = rowMeans(cbind(y1$X2, y2$X2)),
#                      "X3" = rowMeans(cbind(y1$X3, y2$X3)),
#                      "X4" = rowMeans(cbind(y1$X4, y2$X4)),
#                      "X5" = rowMeans(cbind(y1$X5, y2$X5)),
#                      "X6" = rowMeans(cbind(y1$X6, y2$X6)),
#                      "X7" = rowMeans(cbind(y1$X7, y2$X7)),
#                      "X8" = rowMeans(cbind(y1$X8, y2$X8)),
#                      "model" = "joint")
# 
# y_data <- rbind(y1, y2, yjoint)
# 
# meta_data <- read.csv(paste0("data/noisy_a_new_hope_batch", i+1, "/meta_data_n=0.3.csv")) %>%
#   mutate(run_idx = run_idx + (5*i))
# 
# df <- cbind(y_data, meta_data) %>%
#   group_by(model, coupling, run_idx, signal_idx) %>%
#   mutate(timestep = row_number())
# 
# data <- rbind(data, df)
# }
# 
# performance_data <- data %>%
# rowwise() %>%
# mutate(response = which.max(c(X0, X1, X2, X3, X4, X5, X6, X7, X8)),
#        target = which.max(c(TX0, TX1, TX2, TX3, TX4, TX5, TX6, TX7, TX8)),
#        correct = ifelse(response==target, 1, 0))
# 
# write.csv(performance_data, file = "data/noisy_a_new_hope_performance_n=0.3.csv")
```

# load data

```{r}
performance_data <- read.csv("data/test_06_18/performance_n=0.3_nnodes=300.csv") # noisy_a_new_hope_performance.csv
```

```{r}
performance_data <- performance_data %>%
  # filter(timestep != 1) %>%
  mutate(model = factor(model),
         run_idx = factor(run_idx),
         signal_idx = factor(signal_idx),
         target = factor(target))
```

```{r}
# sanity check: check that both esns are comparable

performance_data %>%
  filter(model != "joint", coupling == 0) %>%
  # group_by(model, signal_idx) %>%
  # summarise(sigacc = mean(correct)) %>%
  group_by(model) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))
```

# acc x coupling

```{r}
joint_esn_perf <- performance_data %>% 
  filter(model=="joint") %>%
  group_by(coupling) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))

ggplot(joint_esn_perf, aes(x=as.numeric(coupling), y=m)) +
  geom_point() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title="Joint decision over coupling strengths", x="Coupling", y="Accuracy (%)") +
  theme_bw()

# ggsave(filename = "figures/acc_x_coupling.png", height=7, width=10)
```

```{r}
# benefit of averaging out noise in the readouts vs effect coupled feedback on reservoir dynamics

wjoint <- data.frame(X0 = numeric(),
                     X1 = numeric(),
                     X2 = numeric(),
                     X3 = numeric(),
                     X4 = numeric(),
                     X5 = numeric(),
                     X6 = numeric(),
                     X7 = numeric(),
                     X8 = numeric(),
                     weight = numeric())

for(i in c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)){
  y1 <- performance_data %>%
    filter(model=="1", coupling==0)
  
  y2 <- performance_data %>%
    filter(model=="2", coupling==0)
  
  df <- data.frame(X0 = rowWeightedMeans(cbind(y1$X0, y2$X0), w=c(1-i, i)),
                   X1 = rowWeightedMeans(cbind(y1$X1, y2$X1), w=c(1-i, i)),
                   X2 = rowWeightedMeans(cbind(y1$X2, y2$X2), w=c(1-i, i)),
                   X3 = rowWeightedMeans(cbind(y1$X3, y2$X3), w=c(1-i, i)),
                   X4 = rowWeightedMeans(cbind(y1$X4, y2$X4), w=c(1-i, i)),
                   X5 = rowWeightedMeans(cbind(y1$X5, y2$X5), w=c(1-i, i)),
                   X6 = rowWeightedMeans(cbind(y1$X6, y2$X6), w=c(1-i, i)),
                   X7 = rowWeightedMeans(cbind(y1$X7, y2$X7), w=c(1-i, i)),
                   X8 = rowWeightedMeans(cbind(y1$X8, y2$X8), w=c(1-i, i)),
                   weight = i)
  
  wjoint <- rbind(wjoint, df)
}

meta_data <- performance_data %>%
  filter(model=="joint", coupling==0) %>%
  ungroup() %>%
  select(run_idx, signal_idx, timestep, target)

wjoint <- cbind(wjoint, meta_data) %>%
  rowwise() %>%
  mutate(response = which.max(c(X0, X1, X2, X3, X4, X5, X6, X7, X8)),
         correct = ifelse(response==target, 1, 0)) %>%
  group_by(weight) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))

ggplot(wjoint, aes(x=as.numeric(weight), y=m)) +
  geom_point() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title="Joint decision weight (autofeedback)", x="Weight", y="Accuracy (%)") +
  theme_bw()

# ggsave(filename = "figures/wavg_joint.png", height=7, width=10)
```

# acc over time

```{r}
joint_perf_timeseries <- performance_data %>%
  filter(model=="joint") %>%
  group_by(coupling, run_idx, signal_idx) %>%
  mutate(tnorm = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(tnorm = round(tnorm, 1) * 10) %>%
  group_by(coupling, tnorm) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))

ggplot(joint_perf_timeseries, aes(x=tnorm, y=m)) +
  facet_wrap(~coupling) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title="Accuracy over coupling strengths", x="Time (normalized)", y="Accuracy (%)") +
  theme_bw()
```

```{r}
joint_perf_timeseries <- performance_data %>%
  filter(model=="joint") %>%
  group_by(coupling, run_idx, signal_idx) %>%
  mutate(tnorm = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(tnorm = round(tnorm, 1) * 10) %>%
  group_by(coupling, run_idx, signal_idx) %>%
  arrange(tnorm, .by_group = TRUE) %>%
  mutate(cuml_cor = cumsum(correct),
         cuml_total = row_number(),
         cuml_acc = cuml_cor/cuml_total) %>%
  group_by(coupling, tnorm) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))

ggplot(joint_perf_timeseries, aes(x=tnorm, y=m)) +
  facet_wrap(~coupling) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title="Integrating over time", x="Time (normalized)", y="Accuracy (%)") +
  theme_bw()
```

```{r}
joint_perf_timeseries <- performance_data %>%
  filter(model=="joint") %>%
  group_by(coupling, run_idx, signal_idx) %>%
  mutate(tnorm = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(tnorm = round(tnorm, 1) * 10) %>%
  group_by(coupling, target, tnorm) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))

ggplot(joint_perf_timeseries, aes(x=tnorm, y=m, fill=target, color=target)) +
  facet_wrap(~coupling) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title="Accuracy over coupling strengths", x="Time (normalized)", y="Accuracy (%)", fill="Target", color="Target") +
  scale_color_viridis(discrete = T) +
  theme_bw()
```

```{r}
joint_perf_timeseries <- performance_data %>%
  filter(model=="joint") %>%
  group_by(coupling, run_idx, signal_idx) %>%
  mutate(tnorm = (timestep - min(timestep)) / (max(timestep) - min(timestep))) %>%
  mutate(tnorm = round(tnorm, 1) * 10) %>%
  group_by(coupling, run_idx, signal_idx, target) %>%
  arrange(tnorm, .by_group = TRUE) %>%
  mutate(cuml_cor = cumsum(correct),
         cuml_total = row_number(),
         cuml_acc = cuml_cor/cuml_total) %>%
  group_by(coupling, target, tnorm) %>%
  summarise(m = mean(correct), se = sd(correct)/sqrt(n()))

ggplot(joint_perf_timeseries, aes(x=tnorm, y=m, fill=target, color=target)) +
  facet_wrap(~coupling) +
  geom_point(alpha=0.5) +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.1, linetype = 0) +
  geom_line() +
  labs(title="Integrating over time", x="Time (normalized)", y="Accuracy (%)", fill="Target", color="Target") +
  scale_color_viridis(discrete = T) +
  theme_bw()
```

# PCA

```{r}
meta_data <- read.csv("data/a_new_hope_batch1/meta_data.csv")

r1 <- read.csv("data/a_new_hope_batch1/R1.csv")
r2 <- read.csv("data/a_new_hope_batch1/R2.csv")

colnames(r2) <- paste0('2', colnames(r2))

res_data <- cbind(r1, r2)
```

```{r}
data <- cbind(res_data, meta_data) %>%
  mutate(coupling = factor(coupling),
         signal_idx = factor(signal_idx),
         run_idx = factor(run_idx)) %>%
  group_by(coupling, run_idx, signal_idx) %>%
  mutate(timestep = row_number()) %>%
  filter(run_idx==0)
```

```{r}
var_df <- data.frame(
  comp = numeric(),
  cumvar = numeric(),
  coupling = numeric())

for(i in c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)){
  rstates <- data %>%
    ungroup() %>%
    filter(coupling==i) %>%
    select(!c(coupling, signal_idx, run_idx, timestep, TX0, TX1, TX2, TX3, TX4, TX5, TX6, TX7, TX8))
  
  pca <- prcomp(rstates, center=T, scale.=T)
  
  explained_variance <- pca$sdev^2 / sum(pca$sdev^2)
  cumulative_variance <- cumsum(explained_variance)
  
  vdf <- data.frame(comp = seq_along(cumulative_variance), cumvar = cumulative_variance) %>%
    mutate(coupling = i)
  
  var_df <- rbind(var_df, vdf)
}
```

```{r}
ggplot(var_df %>% filter(coupling %in% c(0.0, 0.2, 0.5, 1.0)), aes(x = comp, y = cumvar, color = as.factor(coupling))) +
  geom_point(size=0.5) +
  geom_line() +
  scale_color_viridis(discrete = T) +
  labs(title = "Cumulative Explained Variance", x = "Principal Component", y = "Cumulative Variance Explained", color = "Coupling") +
  theme_bw()
```

