---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(viridis)
library(entropy)
library(infotheo)
```

# Process data

## Avg. cumulative explained var

```{r}
# cum_var_df <- data.frame(
#   pc = numeric(),
#   cumvar = numeric(),
#   coupling = numeric(),
#   sim = numeric()
# )
# 
# for(run in c(0:9)){
#   for(strength in c("0.0", "0.5", "1.0")){
#     r1 <- read.csv(paste0("data/savedata/r1_cs=", strength, "_r1=500_r2=500_sample=0.5_sim=", run, # ".csv"))
#     r2 <- read.csv(paste0("data/savedata/r2_cs=", strength, "_r1=500_r2=500_sample=0.5_sim=", run, # ".csv"))
#     
#     r_comb <- cbind(r1, r2)
#     
#     scaled_r_comb <- scale(r_comb)
#     pca_result <- prcomp(scaled_r_comb, center = TRUE, scale. = TRUE)
#     
#     var_explained <- pca_result$sdev^2
#     prop_var_explained <- var_explained / sum(var_explained)
#     
#     cum_var_explained <- cumsum(prop_var_explained)
#     
#     temp_df <- data.frame(
#       pc = 1:length(cum_var_explained),
#       cumvar = cum_var_explained,
#       coupling = strength,
#       sim = run
#     )
#     
#     cum_var_df <- rbind(cum_var_df, temp_df)
#   }
# }
# 
# cum_var_df <- cum_var_df %>%
#   group_by(pc, coupling) %>%
#   summarise(avg_cumvar = mean(cumvar), se_cumvar = sd(cumvar)/sqrt(n()))
# 
# # write.csv(cum_var_df, "data/savedata/avg_PCA_variance.csv", row.names = FALSE)
```

## Avg. PCA correlations

```{r}
# Uncoupled

cor_df <- data.frame(
  r1 = integer(),
  r2 = integer(),
  cor = numeric(),
  sim = numeric()
)

for(run in c(0:9)){
  r1 <- read.csv(paste0("data/savedata/r1_cs=0.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
  r2 <- read.csv(paste0("data/savedata/r2_cs=0.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
  
  scaled_r1 <- scale(r1)
  scaled_r2 <- scale(r2)
  
  pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
  pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)
  
  pcs_r1 <- pca_r1$x[, 1:500]
  pcs_r2 <- pca_r2$x[, 1:500]
  
  for(i in 1:500){
   for(j in 1:500){
     vec1 <- pcs_r1[, i]
     vec2 <- pcs_r2[, j]
     
     cor_val <- cor(vec1, vec2)
     
     cor_df <- rbind(cor_df, data.frame(r1 = i, r2 = j, cor = cor_val, sim = run))
   }
  }
}

cor_df <- cor_df %>%
  group_by(r1, r2) %>%
  summarise(avg_cor = mean(cor), se_cor = sd(cor)/sqrt(n()))

write.csv(cor_df, "data/savedata/avg_PCA_correlations_uncoupled.csv", row.names = FALSE)
```

```{r}
# Loosely coupled

cor_df <- data.frame(
  r1 = integer(),
  r2 = integer(),
  cor = numeric(),
  sim = numeric()
)

for(run in c(0:9)){
  r1 <- read.csv(paste0("data/savedata/r1_cs=0.5_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
  r2 <- read.csv(paste0("data/savedata/r2_cs=0.5_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
  
  scaled_r1 <- scale(r1)
  scaled_r2 <- scale(r2)
  
  pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
  pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)
  
  pcs_r1 <- pca_r1$x[, 1:500]
  pcs_r2 <- pca_r2$x[, 1:500]
  
  for(i in 1:500){
   for(j in 1:500){
     vec1 <- pcs_r1[, i]
     vec2 <- pcs_r2[, j]
     
     cor_val <- cor(vec1, vec2)
     
     cor_df <- rbind(cor_df, data.frame(r1 = i, r2 = j, cor = cor_val, sim = run))
   }
  }
}

cor_df <- cor_df %>%
  group_by(r1, r2) %>%
  summarise(avg_cor = mean(cor), se_cor = sd(cor)/sqrt(n()))

write.csv(cor_df, "data/savedata/avg_PCA_correlations_looselycoupled.csv", row.names = FALSE)
```

```{r}
# Tightly coupled

cor_df <- data.frame(
  r1 = integer(),
  r2 = integer(),
  cor = numeric(),
  sim = numeric()
)

for(run in c(0:9)){
  r1 <- read.csv(paste0("data/savedata/r1_cs=1.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
  r2 <- read.csv(paste0("data/savedata/r2_cs=1.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
  
  scaled_r1 <- scale(r1)
  scaled_r2 <- scale(r2)
  
  pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
  pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)
  
  pcs_r1 <- pca_r1$x[, 1:500]
  pcs_r2 <- pca_r2$x[, 1:500]
  
  for(i in 1:500){
   for(j in 1:500){
     vec1 <- pcs_r1[, i]
     vec2 <- pcs_r2[, j]
     
     cor_val <- cor(vec1, vec2)
     
     cor_df <- rbind(cor_df, data.frame(r1 = i, r2 = j, cor = cor_val, sim = run))
   }
  }
}

cor_df <- cor_df %>%
  group_by(r1, r2) %>%
  summarise(avg_cor = mean(cor), se_cor = sd(cor)/sqrt(n()))

write.csv(cor_df, "data/savedata/avg_PCA_correlations_tightlycoupled.csv", row.names = FALSE)
```

## Avg. mutual info

```{r}
bins <- 10
num_pcs <- 50
```

```{r}
# normalized MIs for uncoupled reservoirs

# mi_df <- data.frame(
#   pc = numeric(),
#   nmi = numeric(),
#   sim = numeric()
# )
# 
# for(run in c(0:9)){
#   r1 <- read.csv(paste0("data/savedata/r1_cs=0.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
#   r2 <- read.csv(paste0("data/savedata/r2_cs=0.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
#   
#   scaled_r1 <- scale(r1)
#   scaled_r2 <- scale(r2)
#   
#   pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
#   pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)
#   
#   pcs_r1 <- pca_r1$x[, 1:num_pcs]
#   pcs_r2 <- pca_r2$x[, 1:num_pcs]
#   
#   for(i in 1:num_pcs) {
#     r1_disc <- infotheo::discretize(pcs_r1[, i], nbins = bins)
#     r2_disc <- infotheo::discretize(pcs_r2[, i], nbins = bins)
#   
#     h_r1 <- entropy::entropy(table(r1_disc))
#     h_r2 <- entropy::entropy(table(r2_disc))
#     mi  <- infotheo::mutinformation(r1_disc, r2_disc)
#   
#     temp_df <- data.frame(
#       pc = i,
#       nmi = mi / sqrt(h_r1 * h_r2),
#       sim = run
#     )
#     
#     mi_df <- rbind(mi_df, temp_df)
#   }
# }
# 
# mi_df <- mi_df %>%
#   group_by(pc) %>%
#   summarise(avg_nmi = mean(nmi), se_nmi = sd(nmi)/sqrt(n()))
# 
# write.csv(mi_df, "data/savedata/avg_PCA_mutualinformation_uncoupled.csv", row.names = FALSE)
```

```{r}
# # normalized MIs for loosely coupled reservoirs
# 
# mi_df <- data.frame(
#   pc = numeric(),
#   nmi = numeric(),
#   sim = numeric()
# )
# 
# for(run in c(0:9)){
#   r1 <- read.csv(paste0("data/savedata/r1_cs=0.5_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
#   r2 <- read.csv(paste0("data/savedata/r2_cs=0.5_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
#   
#   scaled_r1 <- scale(r1)
#   scaled_r2 <- scale(r2)
#   
#   pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
#   pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)
#   
#   pcs_r1 <- pca_r1$x[, 1:num_pcs]
#   pcs_r2 <- pca_r2$x[, 1:num_pcs]
#   
#   for(i in 1:num_pcs) {
#     r1_disc <- infotheo::discretize(pcs_r1[, i], nbins = bins)
#     r2_disc <- infotheo::discretize(pcs_r2[, i], nbins = bins)
#   
#     h_r1 <- entropy::entropy(table(r1_disc))
#     h_r2 <- entropy::entropy(table(r2_disc))
#     mi  <- infotheo::mutinformation(r1_disc, r2_disc)
#   
#     temp_df <- data.frame(
#       pc = i,
#       nmi = mi / sqrt(h_r1 * h_r2),
#       sim = run
#     )
#     
#     mi_df <- rbind(mi_df, temp_df)
#   }
# }
# 
# mi_df <- mi_df %>%
#   group_by(pc) %>%
#   summarise(avg_nmi = mean(nmi), se_nmi = sd(nmi)/sqrt(n()))
# 
# write.csv(mi_df, "data/savedata/avg_PCA_mutualinformation_looselycoupled.csv", row.names = FALSE)
```

```{r}
# normalized MIs for tightly coupled reservoirs

# mi_df <- data.frame(
#   pc = numeric(),
#   nmi = numeric(),
#   sim = numeric()
# )
# 
# for(run in c(0:9)){
#   r1 <- read.csv(paste0("data/savedata/r1_cs=1.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
#   r2 <- read.csv(paste0("data/savedata/r2_cs=1.0_r1=500_r2=500_sample=0.5_sim=", run, ".csv"))
#   
#   scaled_r1 <- scale(r1)
#   scaled_r2 <- scale(r2)
#   
#   pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
#   pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)
#   
#   pcs_r1 <- pca_r1$x[, 1:num_pcs]
#   pcs_r2 <- pca_r2$x[, 1:num_pcs]
#   
#   for(i in 1:num_pcs) {
#     r1_disc <- infotheo::discretize(pcs_r1[, i], nbins = bins)
#     r2_disc <- infotheo::discretize(pcs_r2[, i], nbins = bins)
#   
#     h_r1 <- entropy::entropy(table(r1_disc))
#     h_r2 <- entropy::entropy(table(r2_disc))
#     mi  <- infotheo::mutinformation(r1_disc, r2_disc)
#   
#     temp_df <- data.frame(
#       pc = i,
#       nmi = mi / sqrt(h_r1 * h_r2),
#       sim = run
#     )
#     
#     mi_df <- rbind(mi_df, temp_df)
#   }
# }
# 
# mi_df <- mi_df %>%
#   group_by(pc) %>%
#   summarise(avg_nmi = mean(nmi), se_nmi = sd(nmi)/sqrt(n()))
# 
# write.csv(mi_df, "data/savedata/avg_PCA_mutualinformation_tightlycoupled.csv", row.names = FALSE)
```


# Compare cumulative explained variance

```{r}
cum_var_df <- read.csv("data/savedata/avg_PCA_variance.csv") %>%
  mutate(coupling = factor(coupling))

ggplot(cum_var_df, aes(x = pc, y = avg_cumvar, color = coupling)) +
  geom_line() +
  geom_ribbon(aes(ymin = avg_cumvar - se_cumvar, ymax = avg_cumvar + se_cumvar), alpha = 0.1, linetype = 0) +
  scale_color_viridis_d(direction = -1) +
  xlim(1,100) +
  labs(
    x = "PC",
    y = "Avg. Cumulative Proportion of Variance Explained",
    color = "Coupling Weight"
  ) +
  theme_bw()

# ggsave(file = "poster_figs/avg_PCA_cumulative_var.png")
```


# Correlation heatmap: PCA

```{r}
cor_df_none <- read.csv("data/savedata/avg_PCA_correlations_uncoupled.csv")
cor_df_loose <- read.csv("data/savedata/avg_PCA_correlations_looselycoupled.csv")
cor_df_tight <- read.csv("data/savedata/avg_PCA_correlations_tightlycoupled.csv")

cor_df_none$coupling <- "Coupling=0.0"
cor_df_loose$coupling <- "Coupling=0.5"
cor_df_tight$coupling <- "Coupling=1.0"

cor_df <- rbind(cor_df_none, cor_df_loose, cor_df_tight) %>%
  mutate(coupling = factor(coupling, levels = c("Coupling=0.0", "Coupling=0.5", "Coupling=1.0")))

ggplot(cor_df, aes(x = r1, y = r2, fill = avg_cor)) +
  facet_wrap(~coupling) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(
    x = expression(R[1]),
    y = expression(R[2]),
    fill = expression(italic("r"))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        aspect.ratio = 1)

ggsave(file = "poster_figs/avg_PCA_correlations.png")
```


# MI between PCs

```{r}
mi_df_none <- read.csv("data/savedata/avg_PCA_mutualinformation_uncoupled.csv")
mi_df_loose <- read.csv("data/savedata/avg_PCA_mutualinformation_looselycoupled.csv")
mi_df_tight <- read.csv("data/savedata/avg_PCA_mutualinformation_tightlycoupled.csv")

mi_df_none$coupling <- "Coupling=0.0"
mi_df_loose$coupling <- "Coupling=0.5"
mi_df_tight$coupling <- "Coupling=1.0"

mi_df <- rbind(mi_df_none, mi_df_loose, mi_df_tight) %>%
  mutate(coupling = factor(coupling, levels = c("Coupling=0.0", "Coupling=0.5", "Coupling=1.0")))

ggplot(mi_df, aes(x=pc, y=avg_nmi, color=coupling)) +
  geom_line() +
  geom_ribbon(aes(ymin = avg_nmi - se_nmi, ymax = avg_nmi + se_nmi), alpha = 0.1, linetype = 0) +
  scale_color_viridis_d() +
  # xlim(1, 50) +
  labs(
    x = "PC",
    y = bquote("Avg. NMI( " * R[1] * ", " * R[2] * " )")
  ) +
  theme_bw() +
  theme(legend.title = element_blank())

ggsave(file = "poster_figs/avg_PCA_mutualinformation.png")
```

