---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(viridis)
```

```{r}
y1 <- read.csv("data/indiv_run/y1_cs=0.5.csv")
y2 <- read.csv("data/indiv_run/y2_cs=0.5.csv")
yjoint <- read.csv("data/indiv_run/yjoint_cs=0.5.csv")
ytest <- read.csv("data/indiv_run/ytest_cs=0.5.csv")
signal_ids <- read.csv("data/indiv_run/signal_ids.csv")
```

```{r}
y1$response <- max.col(y1)
y2$response <- max.col(y2)
yjoint$response <- max.col(yjoint)

y1$target <- max.col(ytest)
y2$target <- max.col(ytest)
yjoint$target <- max.col(ytest)

y1 <- y1 %>%
  cbind(signal_ids) %>%
  group_by(signal) %>%
  mutate(timestep = row_number(),
         model = "y1")

y2 <- y2 %>%
  cbind(signal_ids) %>%
  group_by(signal) %>%
  mutate(timestep = row_number(),
         model = "y2")

yjoint <- yjoint %>%
  cbind(signal_ids) %>%
  group_by(signal) %>%
  mutate(timestep = row_number(),
         model = "yjoint")
```

```{r}
y1_long <- y1 %>%
  pivot_longer(cols = !c(response, target, signal, timestep, model), names_to = "bit", values_to = "value")

y2_long <- y2 %>%
  pivot_longer(cols = !c(response, target, signal, timestep, model), names_to = "bit", values_to = "value")

yjoint_long <- yjoint %>%
  pivot_longer(cols = !c(response, target, signal, timestep, model), names_to = "bit", values_to = "value")

ycombined_long <- rbind(y1_long, y2_long, yjoint_long) %>%
  group_by(target, signal, model) %>%
  mutate(scaled = (value - min(value)) / (max(value) - min(value)))

ggplot(ycombined_long %>% filter(target==1, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==2, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==3, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==4, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==5, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==6, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==7, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==8, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

```{r}
ggplot(ycombined_long %>% filter(target==9, model=="yjoint"), aes(x = timestep, y = bit, fill = scaled)) +
  facet_wrap(~signal, scales = "free_x") +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(x = "Timestep", y = "Bit", fill = "Value") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_blank())
```

