---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(viridis)
library(entropy)
library(infotheo)
library(RTransferEntropy)
```

# Compare cumulative explained variance

```{r}
cum_var_df <- data.frame(
  pc = numeric(),
  cumvar = numeric(),
  coupling = numeric()
)

for(strength in c("0.0", "0.5", "1.0")){
  r1 <- read.csv(paste0("data/indiv_run/r1_cs=", strength, "_r1=500_r2=500_sample=0.5.csv"))
  r2 <- read.csv(paste0("data/indiv_run/r2_cs=", strength, "_r1=500_r2=500_sample=0.5.csv"))
  
  r_comb <- cbind(r1, r2)
  
  scaled_r_comb <- scale(r_comb)
  pca_result <- prcomp(scaled_r_comb, center = TRUE, scale. = TRUE)
  
  var_explained <- pca_result$sdev^2
  prop_var_explained <- var_explained / sum(var_explained)
  
  cum_var_explained <- cumsum(prop_var_explained)
  
  temp_df <- data.frame(
    pc = 1:length(cum_var_explained),
    cumvar = cum_var_explained,
    coupling = strength
  )
  
  cum_var_df <- rbind(cum_var_df, temp_df)
}

cum_var_df$coupling <- factor(cum_var_df$coupling)
```

```{r}
ggplot(cum_var_df, aes(x = pc, y = cumvar, color = coupling)) +
  geom_line(size=1) +
  scale_color_viridis_d(direction = -1) +
  xlim(1,100) +
  labs(
    x = "PC",
    y = "Cumulative Proportion of Variance Explained",
    color = "Coupling Weight"
  ) +
  theme_bw()
```

# Correlation heatmap

```{r}
r1 <- read.csv("data/indiv_run/r1_cs=1.0_r1=500_r2=500_sample=0.5.csv")
r2 <- read.csv("data/indiv_run/r2_cs=1.0_r1=500_r2=500_sample=0.5.csv")

cor_df <- data.frame(
 r1 = integer(),
 r2 = integer(),
 cor = numeric()
)

for(i in 0:499){
 for(j in 0:499){
   actvec1 <- r1[[paste0("X", i)]]
   actvec2 <- r2[[paste0("X", j)]]
   
   cor_val <- cor(actvec1, actvec2)
   
   cor_df <- rbind(cor_df, data.frame(r1 = i, r2 = j, cor = cor_val))
 }
}

# write.csv(cor_df, "data/indiv_run/r12_corcoeff_cs=0.5_r1=500_r2=500_sample=0.5.csv", row.names = FALSE)
# write.csv(cor_df, "data/indiv_run/r12_corcoeff_cs=0.0_r1=500_r2=500_sample=0.5.csv", row.names = FALSE)
# write.csv(cor_df, "data/indiv_run/r12_corcoeff_cs=1.0_r1=500_r2=500_sample=0.5.csv", row.names = FALSE)
```

```{r}
cor_df_loose <- read.csv("data/indiv_run/r12_corcoeff_cs=0.5_r1=500_r2=500_sample=0.5.csv")
cor_df_none <- read.csv("data/indiv_run/r12_corcoeff_cs=0.0_r1=500_r2=500_sample=0.5.csv")
cor_df_tight <- read.csv("data/indiv_run/r12_corcoeff_cs=1.0_r1=500_r2=500_sample=0.5.csv")

ggplot(cor_df_loose, aes(x = r1, y = r2, fill = cor)) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(
    title = "coupling weight = 0.5",
    x = expression(R[1]),
    y = expression(R[2]),
    fill = expression(italic("r"))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank())

ggplot(cor_df_none, aes(x = r1, y = r2, fill = cor)) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(
    title = "coupling weight = 0.0",
    x = expression(R[1]),
    y = expression(R[2]),
    fill = expression(italic("r"))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank())

ggplot(cor_df_tight, aes(x = r1, y = r2, fill = cor)) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(
    title = "coupling weight = 1.0",
    x = expression(R[1]),
    y = expression(R[2]),
    fill = expression(italic("r"))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank())
```

# Correlation heatmap: PCA

```{r}
r1 <- read.csv("data/indiv_run/r1_cs=1.0_r1=500_r2=500_sample=0.5.csv")
r2 <- read.csv("data/indiv_run/r2_cs=1.0_r1=500_r2=500_sample=0.5.csv")

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:500]
pcs_r2 <- pca_r2$x[, 1:500]

cor_df <- data.frame(
 r1 = integer(),
 r2 = integer(),
 cor = numeric()
)

for(i in 1:500){
 for(j in 1:500){
   vec1 <- pcs_r1[, i]
   vec2 <- pcs_r2[, j]
   
   cor_val <- cor(vec1, vec2)
   
   cor_df <- rbind(cor_df, data.frame(r1 = i, r2 = j, cor = cor_val))
 }
}

# write.csv(cor_df, "data/indiv_run/r12_PCAcorcoeff_cs=0.0_r1=500_r2=500_sample=0.5.csv", row.names = FALSE)
# write.csv(cor_df, "data/indiv_run/r12_PCAcorcoeff_cs=0.5_r1=500_r2=500_sample=0.5.csv", row.names = FALSE)
# write.csv(cor_df, "data/indiv_run/r12_PCAcorcoeff_cs=1.0_r1=500_r2=500_sample=0.5.csv", row.names = FALSE)
```

```{r}
cor_df_none <- read.csv("data/indiv_run/r12_PCAcorcoeff_cs=0.0_r1=500_r2=500_sample=0.5.csv")
cor_df_loose <- read.csv("data/indiv_run/r12_PCAcorcoeff_cs=0.5_r1=500_r2=500_sample=0.5.csv")
cor_df_tight <- read.csv("data/indiv_run/r12_PCAcorcoeff_cs=1.0_r1=500_r2=500_sample=0.5.csv")

cor_df_none$coupling <- "Uncoupled"
cor_df_loose$coupling <- "Loosely coupled"
cor_df_tight$coupling <- "Tightly coupled"

cor_df <- rbind(cor_df_none, cor_df_loose, cor_df_tight) %>%
  mutate(coupling = factor(coupling, levels = c("Loosely coupled", "Uncoupled", "Tightly coupled")))

ggplot(cor_df, aes(x = r1, y = r2, fill = cor)) +
  facet_wrap(~coupling) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(
    x = expression(R[1]),
    y = expression(R[2]),
    fill = expression(italic("r"))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        aspect.ratio = 1)
```

# MI between PCs

```{r}
bins <- 10
num_pcs <- 50


# normalized MIs for uncoupled reservoirs

r1 <- read.csv(paste0("data/indiv_run/r1_cs=0.0_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=0.0_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:num_pcs]
pcs_r2 <- pca_r2$x[, 1:num_pcs]

mi_values_uncoupled <- numeric(num_pcs)

for (i in 1:num_pcs) {
  r1_disc <- infotheo::discretize(pcs_r1[, i], nbins = bins)
  r2_disc <- infotheo::discretize(pcs_r2[, i], nbins = bins)

  h_r1 <- entropy::entropy(table(r1_disc))
  h_r2 <- entropy::entropy(table(r2_disc))
  mi  <- infotheo::mutinformation(r1_disc, r2_disc)

  mi_values_uncoupled[i] <- mi / sqrt(h_r1 * h_r2)
}


# normalized MIs for loosely coupled reservoirs

r1 <- read.csv(paste0("data/indiv_run/r1_cs=0.5_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=0.5_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:num_pcs]
pcs_r2 <- pca_r2$x[, 1:num_pcs]

mi_values_loose <- numeric(num_pcs)

for (i in 1:num_pcs) {
  r1_disc <- infotheo::discretize(pcs_r1[, i], nbins = bins)
  r2_disc <- infotheo::discretize(pcs_r2[, i], nbins = bins)

  h_r1 <- entropy::entropy(table(r1_disc))
  h_r2 <- entropy::entropy(table(r2_disc))
  mi  <- infotheo::mutinformation(r1_disc, r2_disc)

  mi_values_loose[i] <- mi / sqrt(h_r1 * h_r2)
}


# normalized MIs for tightly coupled reservoirs

r1 <- read.csv(paste0("data/indiv_run/r1_cs=1.0_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=1.0_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:num_pcs]
pcs_r2 <- pca_r2$x[, 1:num_pcs]

mi_values_tight <- numeric(num_pcs)

for (i in 1:num_pcs) {
  r1_disc <- infotheo::discretize(pcs_r1[, i], nbins = bins)
  r2_disc <- infotheo::discretize(pcs_r2[, i], nbins = bins)

  h_r1 <- entropy::entropy(table(r1_disc))
  h_r2 <- entropy::entropy(table(r2_disc))
  mi  <- infotheo::mutinformation(r1_disc, r2_disc)

  mi_values_tight[i] <- mi / sqrt(h_r1 * h_r2)
}
```

```{r}
mi_df <- data.frame(
  pc = rep(c(1:length(mi_values_uncoupled)), 3),
  mi = c(mi_values_uncoupled, mi_values_loose, mi_values_tight),
  strength = c(rep(0.0, length(mi_values_uncoupled)), rep(0.5, length(mi_values_loose)), rep(1.0, length(mi_values_tight)))
) %>%
  mutate(strength = factor(strength))

ggplot(mi_df, aes(x=pc, y=mi, color=strength)) +
  geom_line() +
  scale_color_viridis_d() +
  # xlim(1, 50) +
  labs(
    x = "PC",
    y = bquote("NMI( " * R[1] * ", " * R[2] * " )"),
    color = "Coupling weight"
  ) +
  theme_bw()
```

```{r}
summary(lm(mi ~ strength, data = mi_df %>% mutate(strength = factor(strength, levels = c(0.5, 0.0, 1.0))) %>% filter(pc < 31)))
```

# Cosine similarity of trajectory derivatives

```{r}
cosine_similarity <- function(u, v) {
  dot <- sum(u * v)
  norm_u <- sqrt(sum(u^2))
  norm_v <- sqrt(sum(v^2))
  if (norm_u == 0 || norm_v == 0) return(NA)  # Handle zero vectors
  dot / (norm_u * norm_v)
}
```

```{r}
r1 <- read.csv(paste0("data/indiv_run/r1_cs=0.5_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=0.5_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

r_comb <- rbind(scaled_r1, scaled_r2)

pca <- prcomp(r_comb, center = TRUE, scale. = TRUE)

pcs_r1 <- predict(pca, newdata = r1)
pcs_r2 <- predict(pca, newdata = r2)
```

```{r}
vel_r1 <- diff(as.matrix(pcs_r1))
vel_r2 <- diff(as.matrix(pcs_r2))

cosine_sims <- sapply(1:nrow(vel_r1), function(t) {
  cosine_similarity(vel_r1[t, ], vel_r2[t, ])
})

plot(cosine_sims, type = "l", main = "Cosine Similarity of Velocity Vectors", ylab = "Cosine Similarity", xlab = "Time Step")
abline(h = mean(cosine_sims, na.rm = TRUE), col = "red", lty = 2)

mean_cos_sim <- mean(cosine_sims, na.rm = TRUE)
print(mean_cos_sim)
```

# Transfer entropy

```{r}
num_pcs <- 10


# TE for uncoupled reservoirs

r1 <- read.csv(paste0("data/indiv_run/r1_cs=0.0_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=0.0_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:num_pcs]
pcs_r2 <- pca_r2$x[, 1:num_pcs]

te12_values_uncoupled <- numeric(num_pcs)
te21_values_uncoupled <- numeric(num_pcs)

for (i in 1:num_pcs) {
  results <- RTransferEntropy::transfer_entropy(pcs_r1[, i], pcs_r2[, i], lx = 1, ly = 1, nboot = 100)
  
  te12 <- results$coef[1]  
  te21 <- results$coef[2]  
  
  te12_values_uncoupled[i] <- te12
  te21_values_uncoupled[i] <- te21
}


# TE for loosely coupled reservoirs

r1 <- read.csv(paste0("data/indiv_run/r1_cs=0.5_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=0.5_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:num_pcs]
pcs_r2 <- pca_r2$x[, 1:num_pcs]

te12_values_loose <- numeric(num_pcs)
te21_values_loose <- numeric(num_pcs)

for (i in 1:num_pcs) {
  results <- RTransferEntropy::transfer_entropy(pcs_r1[, i], pcs_r2[, i], lx = 1, ly = 1, nboot = 100)
  
  te12 <- results$coef[1]  
  te21 <- results$coef[2]  
  
  te12_values_loose[i] <- te12
  te21_values_loose[i] <- te21
}


# TE for tightly coupled reservoirs

r1 <- read.csv(paste0("data/indiv_run/r1_cs=1.0_r1=500_r2=500_sample=0.5.csv"))
r2 <- read.csv(paste0("data/indiv_run/r2_cs=1.0_r1=500_r2=500_sample=0.5.csv"))

scaled_r1 <- scale(r1)
scaled_r2 <- scale(r2)

pca_r1 <- prcomp(scaled_r1, center = TRUE, scale. = TRUE)
pca_r2 <- prcomp(scaled_r2, center = TRUE, scale. = TRUE)

pcs_r1 <- pca_r1$x[, 1:num_pcs]
pcs_r2 <- pca_r2$x[, 1:num_pcs]

te12_values_tight <- numeric(num_pcs)
te21_values_tight <- numeric(num_pcs)

for (i in 1:num_pcs) {
  results <- RTransferEntropy::transfer_entropy(pcs_r1[, i], pcs_r2[, i], lx = 1, ly = 1, nboot = 100)
  
  te12 <- results$coef[1]  
  te21 <- results$coef[2]  
  
  te12_values_tight[i] <- te12
  te21_values_tight[i] <- te21
}
```

```{r}
te12_df <- data.frame(
  pc = rep(c(1:length(te12_values_uncoupled)), 3),
  te = c(te12_values_uncoupled, te12_values_loose, te12_values_tight),
  strength = c(rep(0.0, length(te12_values_uncoupled)), rep(0.5, length(te12_values_loose)), rep(1.0, length(te12_values_tight)))
) %>%
  mutate(strength = factor(strength))

te21_df <- data.frame(
  pc = rep(c(1:length(te21_values_uncoupled)), 3),
  te = c(te21_values_uncoupled, te21_values_loose, te21_values_tight),
  strength = c(rep(0.0, length(te21_values_uncoupled)), rep(0.5, length(te21_values_loose)), rep(1.0, length(te21_values_tight)))
) %>%
  mutate(strength = factor(strength))

ggplot(te12_df, aes(x=pc, y=te, color=strength)) +
  geom_line() +
  scale_color_viridis_d() +
  labs(
    x = "PC",
    y = expression(T[R[1] %->% R[2]]),
    color = "Coupling weight"
  ) +
  theme_bw()

ggplot(te21_df, aes(x=pc, y=te, color=strength)) +
  geom_line() +
  scale_color_viridis_d() +
  labs(
    x = "PC",
    y = expression(T[R[2] %->% R[1]]),
    color = "Coupling weight"
  ) +
  theme_bw()
```

