---
title: "State Space Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(viridis)
```

# 0.0

## Load and clean data

```{r}
meta_data <- read.csv("data/s23_randreset_batch1/meta_data.csv")

r1 <- read.csv(paste0("data/s23_randreset_batch1/R1_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.0")

r2 <- read.csv(paste0("data/s23_randreset_batch1/R2_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata1 <- rbind(r1, r2)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch2/R1_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.0")

r2 <- read.csv(paste0("data/s23_randreset_batch2/R2_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata2 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 8)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch3/R1_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.0")

r2 <- read.csv(paste0("data/s23_randreset_batch3/R2_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata3 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 16)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch4/R1_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.0")

r2 <- read.csv(paste0("data/s23_randreset_batch4/R2_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata4 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 24)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch5/R1_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.0")

r2 <- read.csv(paste0("data/s23_randreset_batch5/R2_cs=0.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata5 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 32)
```

```{r}
rdata <- rbind(rdata1, rdata2, rdata3, rdata4, rdata5)
```

## PCA

```{r}
rdata <- rdata %>%
  group_by(run_idx, model, coupling, signal_idx) %>%
  mutate(timestep = row_number())
```

```{r}
res1_nodes <- rdata %>%
  ungroup() %>%
  filter(model==1) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

res2_nodes <- rdata %>%
  ungroup() %>%
  filter(model==2) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

colnames(res2_nodes) <- paste0('2_', colnames(res2_nodes))

pca_data <- cbind(res1_nodes, res2_nodes)



# pca_data <- rdata %>%
#   ungroup() %>%
#   select(!c(model, coupling, signal_idx, run_idx, timestep))


pca <- prcomp(pca_data, center=T, scale.=T)
```

```{r}
explained_variance_0 <- pca$sdev^2 / sum(pca$sdev^2)
cumulative_variance_0 <- cumsum(explained_variance_0)

variance_df_0 <- data.frame(comp = seq_along(cumulative_variance_0),
                            cumvar = cumulative_variance_0)

ggplot(variance_df_0, aes(x = comp, y = cumvar)) +
  geom_point() +
  geom_line() +
  labs(title = "Cumulative Explained Variance", x = "Principal Component", y = "Cumulative Variance Explained") +
  theme_bw()
```

# 0.2

## Load and clean data

```{r}
meta_data <- read.csv("data/s23_randreset_batch1/meta_data.csv")

r1 <- read.csv(paste0("data/s23_randreset_batch1/R1_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.2")

r2 <- read.csv(paste0("data/s23_randreset_batch1/R2_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.2")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata1 <- rbind(r1, r2)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch2/R1_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.2")

r2 <- read.csv(paste0("data/s23_randreset_batch2/R2_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.2")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata2 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 8)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch3/R1_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.2")

r2 <- read.csv(paste0("data/s23_randreset_batch3/R2_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.2")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata3 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 16)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch4/R1_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.2")

r2 <- read.csv(paste0("data/s23_randreset_batch4/R2_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.2")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata4 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 24)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch5/R1_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.2")

r2 <- read.csv(paste0("data/s23_randreset_batch5/R2_cs=0.2_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.2")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata5 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 32)
```

```{r}
rdata <- rbind(rdata1, rdata2, rdata3, rdata4, rdata5)
```

## PCA

```{r}
rdata <- rdata %>%
  group_by(run_idx, model, coupling, signal_idx) %>%
  mutate(timestep = row_number())
```

```{r}
res1_nodes <- rdata %>%
  ungroup() %>%
  filter(model==1) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

res2_nodes <- rdata %>%
  ungroup() %>%
  filter(model==2) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

colnames(res2_nodes) <- paste0('2_', colnames(res2_nodes))

pca_data <- cbind(res1_nodes, res2_nodes)



# pca_data <- rdata %>%
#   ungroup() %>%
#   select(!c(model, coupling, signal_idx, run_idx, timestep))


pca <- prcomp(pca_data, center=T, scale.=T)
```

```{r}
explained_variance_0.2 <- pca$sdev^2 / sum(pca$sdev^2)
cumulative_variance_0.2 <- cumsum(explained_variance_0.2)

variance_df_0.2 <- data.frame(comp = seq_along(cumulative_variance_0.2),
                            cumvar = cumulative_variance_0.2)

ggplot(variance_df_0.2, aes(x = comp, y = cumvar)) +
  geom_point() +
  geom_line() +
  labs(title = "Cumulative Explained Variance", x = "Principal Component", y = "Cumulative Variance Explained") +
  theme_bw()
```

# 0.5

## Load and clean data

```{r}
meta_data <- read.csv("data/s23_randreset_batch1/meta_data.csv")

r1 <- read.csv(paste0("data/s23_randreset_batch1/R1_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.5")

r2 <- read.csv(paste0("data/s23_randreset_batch1/R2_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.5")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata1 <- rbind(r1, r2)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch2/R1_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.5")

r2 <- read.csv(paste0("data/s23_randreset_batch2/R2_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.5")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata2 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 8)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch3/R1_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.5")

r2 <- read.csv(paste0("data/s23_randreset_batch3/R2_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.5")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata3 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 16)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch4/R1_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.5")

r2 <- read.csv(paste0("data/s23_randreset_batch4/R2_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.5")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata4 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 24)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch5/R1_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "0.5")

r2 <- read.csv(paste0("data/s23_randreset_batch5/R2_cs=0.5_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "0.5")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata5 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 32)
```

```{r}
rdata <- rbind(rdata1, rdata2, rdata3, rdata4, rdata5)
```

## PCA

```{r}
rdata <- rdata %>%
  group_by(run_idx, model, coupling, signal_idx) %>%
  mutate(timestep = row_number())
```

```{r}
res1_nodes <- rdata %>%
  ungroup() %>%
  filter(model==1) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

res2_nodes <- rdata %>%
  ungroup() %>%
  filter(model==2) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

colnames(res2_nodes) <- paste0('2_', colnames(res2_nodes))

pca_data <- cbind(res1_nodes, res2_nodes)

# pca_data <- rdata %>%
#   ungroup() %>%
#   select(!c(model, coupling, signal_idx, run_idx, timestep))

pca <- prcomp(pca_data, center=T, scale.=T)
```

```{r}
explained_variance_0.5 <- pca$sdev^2 / sum(pca$sdev^2)
cumulative_variance_0.5 <- cumsum(explained_variance_0.5)

variance_df_0.5 <- data.frame(comp = seq_along(cumulative_variance_0.5),
                            cumvar = cumulative_variance_0.5)

ggplot(variance_df_0.5, aes(x = comp, y = cumvar)) +
  geom_point() +
  geom_line() +
  labs(title = "Cumulative Explained Variance", x = "Principal Component", y = "Cumulative Variance Explained") +
  theme_bw()
```

# 1.0

## Load and clean data

```{r}
meta_data <- read.csv("data/s23_randreset_batch1/meta_data.csv")

r1 <- read.csv(paste0("data/s23_randreset_batch1/R1_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "1.0")

r2 <- read.csv(paste0("data/s23_randreset_batch1/R2_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "1.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata1 <- rbind(r1, r2)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch2/R1_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "1.0")

r2 <- read.csv(paste0("data/s23_randreset_batch2/R2_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "1.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata2 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 8)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch3/R1_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "1.0")

r2 <- read.csv(paste0("data/s23_randreset_batch3/R2_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "1.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata3 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 16)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch4/R1_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "1.0")

r2 <- read.csv(paste0("data/s23_randreset_batch4/R2_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "1.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata4 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 24)
```

```{r}
r1 <- read.csv(paste0("data/s23_randreset_batch5/R1_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 1, coupling = "1.0")

r2 <- read.csv(paste0("data/s23_randreset_batch5/R2_cs=1.0_ns=0.0_r1=100_r2=100.csv")) %>%
  select(!X) %>%
  mutate(model = 2, coupling = "1.0")

r1 <- cbind(r1, meta_data)
r2 <- cbind(r2, meta_data)

rdata5 <- rbind(r1, r2) %>%
  mutate(run_idx = run_idx + 32)
```

```{r}
rdata <- rbind(rdata1, rdata2, rdata3, rdata4, rdata5)
```

## PCA

```{r}
rdata <- rdata %>%
  group_by(run_idx, model, coupling, signal_idx) %>%
  mutate(timestep = row_number())
```

```{r}
res1_nodes <- rdata %>%
  ungroup() %>%
  filter(model==1) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

res2_nodes <- rdata %>%
  ungroup() %>%
  filter(model==2) %>%
  select(!c(model, coupling, signal_idx, run_idx, timestep))

colnames(res2_nodes) <- paste0('2_', colnames(res2_nodes))

pca_data <- cbind(res1_nodes, res2_nodes)

# pca_data <- rdata %>%
#   ungroup() %>%
#   select(!c(model, coupling, signal_idx, run_idx, timestep))

pca <- prcomp(pca_data, center=T, scale.=T)
```

```{r}
explained_variance_1 <- pca$sdev^2 / sum(pca$sdev^2)
cumulative_variance_1 <- cumsum(explained_variance_1)

variance_df_1 <- data.frame(comp = seq_along(cumulative_variance_1),
                            cumvar = cumulative_variance_1)

ggplot(variance_df_1, aes(x = comp, y = cumvar)) +
  geom_point() +
  geom_line() +
  labs(title = "Cumulative Explained Variance", x = "Principal Component", y = "Cumulative Variance Explained") +
  theme_bw()
```

# Together

```{r}
variance_df_0$coupling = 0.0
variance_df_0.2$coupling = 0.2
variance_df_0.5$coupling = 0.5
variance_df_1$coupling = 1.0

variance_df <- rbind(variance_df_0, variance_df_0.2, variance_df_0.5, variance_df_1) %>%
  mutate(coupling = factor(coupling))
```

```{r}
ggplot(variance_df, aes(x = comp, y = cumvar, color = coupling)) +
  geom_point(size=0.5) +
  geom_line() +
  labs(title = "Cumulative Explained Variance",
       x = "Principal Component", y = "Cumulative Variance Explained") +
  theme_bw()
```




